### ISSUE TITLE
如果是 npm i xxx 是不是拦截不了

### ISSUE THREAD

**Issue by qinjialei24** [justjavac/please-use-yarn#1]
如题

**Comment by justjavac** [comment]
是的：

> Runs on local `npm install` **without any arguments**

`preinstall` 只会在没有参数的 `npm install` 和 `npm ci` 之前运行。

**Comment by justjavac** [comment]
如果使用了 npm 安装，会导致 package.json 和 yarn.lock 不一致。可以在 ci 环境上使用 `yarn --ignore-scripts --frozen-lockfile` 来校验。

```
--frozen-lockfile     don't generate a lockfile and fail if an update is needed
```
