### ISSUE TITLE
为什么必须用yarn呢？

### ISSUE THREAD

**Issue by Hanggi** [justjavac/please-use-yarn#2]
包管理工具很多，为什么一定要用yarn呢？

**Comment by huan** [comment]
I have the same question, is there anyone can help us understand which behavior is NPM v8 can not do, or it's not as good as yarn?

**Comment by justjavac** [comment]
这是我自己用的，没想到这么多人 star 了😄

**Comment by huan** [comment]
I saw your project from the Google recommendations in my chrome! :D
